name: pilates
description: "Curve Pilates App"
version: 1.0.1+6

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  flutter_masked_text2: ^0.9.1
  table_calendar: ^3.1.2
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  loading_animation_widget: ^1.2.1
  url_launcher: ^6.2.6
  map_launcher: ^3.3.0
  geolocator: ^11.0.1
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.1
  amazon_s3_cognito: ^0.8.1
  fl_chart: ^0.69.0
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.14.2
  local_auth: ^2.3.0
  go_router: ^14.6.2
  pin_code_fields: ^8.0.1
  path_provider: ^2.1.5
  pdf: ^3.11.1
  flutter_pdfview: ^1.4.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/logo/
    - assets/images/
    - assets/images/menu/
    - assets/images/activities/
    - assets/icons/
    - assets/animations/
    - assets/images/onboarding/

  